# Generated by Django 4.1.1 on 2022-10-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('company', models.JSONField(null=True)),
                ('projects', models.JSONField(null=True)),
                ('designation', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
